[client]
showSidebarNavigation = false

[theme]
primaryColor = "#4F46E5"    # Um roxo/azul moderno (Indigo)
backgroundColor = "#FFFFFF" # Fundo limpo
secondaryBackgroundColor = "#F3F4F6" # Cinza bem claro para sidebar e inputs
textColor = "#1F2937"       # Cinza escuro (quase preto) para leitura confort√°vel
font = "sans serif"

[server]
runOnSave = true