GOOGLE_API_KEY = "AIzaSyBWcVUqSI-5gzdhh3cekVIfty1I-Opy9Qo"
MONGO_URI = "mongodb+srv://souzaaraujo_db_user:g6NbZsuur7QWIyMe@cluster0.oetjxrx.mongodb.net/?appName=Cluster0"
MONGO_DB_NAME = "embeddings"
MONGO_COLLECTION_NAME = "embeddings"

[mongo]
uri = "mongodb+srv://souzaaraujo_db_user:g6NbZsuur7QWIyMe@cluster0.oetjxrx.mongodb.net/?appName=Cluster0"
db_name = "sistema_curriculo"

# CASO PARA INSERIR NO STREAMLIT
# [mongo]
# uri = "mongodb+srv://souzaaraujo_db_user:g6NbZsuur7QWIyMe@cluster0.oetjxrx.mongodb.net/?retryWrites=true&w=majority"
# db_name = "sistema_curriculo"